apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMQ__Host: rabbit-clusterip
  RabbitMQ__Username: rabbit
  RabbitMQ__Password: rabbitpw
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
  IdentityServiceUrl: http://identity-svc
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMQ__Username: rabbit
  RabbitMQ__Password: rabbitpw
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMQ__Username: rabbit
  RabbitMQ__Password: rabbitpw
  ConnectionStrings__BidDbConnection: mongodb://root:mongopw@mongo-clusterip
  IdentityServiceUrl: http://identity-clusterip
  GrpcAuction: http://auction-clusterip:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMQ__Username: rabbit
  RabbitMQ__Password: rabbitpw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ClientApp: https://app.carsties.com
  IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.carsties.com
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=identity
  VIRTUAL_HOST: https://id.carsties.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  NEXTAUTH_SECRET: somethingreallysecret
  NEXTAUTH_URL: https://app.carsties.com
  NEXTAUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL: http://gateway-clusterip/
  ID_URL: http://id.carsties.com
  NEXT_PUBLIC_NOTIFY_URL: https://gateway-clusterip/notifications

